config/routes.rb
Eharbor::Application.routes.draw do

  devise_for :users

  resources :listings do
    resources :bids
  end
  

  root :to => "listings#index"

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing

  validates :user_id, :listing_id, :amount, :presence => true, :numericality => true
  validate :verify_minimum_bid
  validate :verify_active_listing
  
  attr_accessible :amount
  
private

  def verify_minimum_bid
    if listing.highest_bid && amount && listing.highest_bid.amount >= amount
      errors.add :amount, 'must be more than highest bid.'
    end
  end
  
  def verify_active_listing
    errors.add :base, 'This listing has expired.' unless listing.active?
  end
  
end

app/models/bid_mailer.rb
class BidMailer < ActionMailer::Base
  
  def outbid_notification(bid)
    from "eHarbor <app@example.com>"
    recipients "#{bid.user.nickname} <#{bid.user.email}>"
    subject "You have been outbid"
    body :bid => bid
  end
  
  def seller_notification(bid)
    from "eHarbor <app@example.com>"
    recipients "#{bid.listing.user.nickname} <#{bid.listing.user.email}>"
    subject "New bid"
    body :bid => bid
  end
end

app/models/bid_observer.rb
class BidObserver < ActiveRecord::Observer
  
  def after_create(bid)
    if previous_bid = bid.listing.bids.first(:order => 'bids.amount DESC', :offset => 1)
      BidMailer.outbid_notification(previous_bid).deliver
    end
    BidMailer.seller_notification(bid).deliver
  end
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :title, :description

  belongs_to :user
  has_many :bids

  validates_presence_of :title, :description
  validates_inclusion_of :duration, :in => [3, 5, 7]
  
  before_save :calculate_end_at
  
  scope :recent, order('listings.created_at DESC')
  
  scope :active, lambda {
    recent.where(['listings.created_at <= :now AND listings.end_at >= :now', {:now => Time.zone.now}])
  }

  attr_accessible :title, :description, :duration
  
  def highest_bid
    bids.order('bids.amount DESC').first
  end
  
  def active?
    end_at > Time.zone.now
  end
  
private
  
  def calculate_end_at
    self.end_at = (created_at || Time.zone.now) + duration.days
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :listings
  has_many :bids

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @listing = Listing.find(params[:listing_id])
    @bid = @listing.bids.build(params[:bid])
    @bid.user = current_user
    if @bid.save
      respond_to do |format|
        format.html do
          flash[:notice] = 'Your bid saved successfully.'
          redirect_to @listing
        end
        format.js
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:alert] = 'Your bid has an error.'
          render 'listings/show'
        end
        format.js { render 'create_failed' }
      end
    end
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  def index
    @listings = Listing.active
  end
  
  def show
    @listing = Listing.find(params[:id])
  end
  
  def new
    @listing = Listing.new
  end
  
  def create
    @listing = current_user.listings.build(params[:listing])
    if @listing.save
      redirect_to @listing
    else
      render :new
    end
  end
  
  def edit
    @listing = current_user.listings.find(params[:id])
  end
  
  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update_attributes params[:listing]
      redirect_to @listing
    else
      render :edit
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_filter :authenticate, :only => [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/bids/_form.html.erb
<%= form_for [@listing, @bid || Bid.new], :remote => true do |f| %>
  <% if f.object.errors[:amount].present? %>
    <p id="errorExplanation">Your bid <%= f.object.errors[:amount].to_sentence %></p>
  <% end %>
  
  <%= f.label :amount %>
  <%= f.text_field :amount, :size => 6 %>
  <%= f.submit "Bid" %>
<% end %>

app/views/bids/create.js.erb
$('#bid').html('Thanks for the bid of <%= number_to_currency @bid.amount %>');
$('.info').replaceWith('<%= escape_javascript render("listings/info") %>');

app/views/bids/create_failed.js.erb
$('#new_bid').replaceWith('<%= escape_javascript render("bids/form") %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>eHarbor</title>
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <div id="main">
    <header>
      <div id="toolbar">
        <% if user_signed_in? %>
          Signed in as <%= link_to current_user, edit_user_registration_path %> |
          <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> |
          <%= link_to "Register", new_user_registration_path %>
        <% end %>
      </div>
      <h1>
        <%= link_to '<span class="e1">e</span><span class="h2">H</span><span class="a3">a</span><span class="r4">r</span><span class="b5">b</span><span class="o6">o</span><span class="r7">r</span>'.html_safe, root_path %>
      </h1>
      <nav>
        <ul>
          <li><%= link_to "Buy", listings_path %></li>
          <li><%= link_to "Sell", new_listing_path %></li>
        </ul>
      </nav>
    </header>
    <% if notice %><p class="notice"><%= notice %></p><% end %>
    <% if alert %><p class="alert"><%= alert %></p><% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>

  <% if @listing.errors.any? %>
    <div id="errorExplanation">
      <h2>The following errors prohibited this form from being saved:</h2>
      <ul>
        <% @listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.label :duration %><br/>
    <%= f.select :duration, [['3 days', 3], ['5 days', 5], ['7 days', 7]] %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/listings/_info.html.erb
<dl class="info" id="info">
  <dt>Seller:</dt>
  <dd>
    <%= @listing.user %>
    <% if user_signed_in? && current_user == @listing.user %>
      (<%= link_to 'Edit', edit_listing_path(@listing) %>)
    <% end %>
  </dd>
  <% if @listing.highest_bid %>
    <dt>Highest Bid:</dt>
    <dd>
      <%= number_to_currency(@listing.highest_bid.amount) %>
      (<%= @listing.highest_bid.user %>)
    </dd>
  <% end %>
  <dt>History:</dt>
  <dd><%= pluralize @listing.bids.count, 'bid' %></dd>
  <% if @listing.active? %>
    <dt>End time:</dt>
    <dd>
      <%= distance_of_time_in_words_to_now @listing.end_at, true %>
      (<%= @listing.end_at.to_s(:listing) %>)
    </dd>
  <% end %>
</dl>

app/views/listings/_listing.html.erb
<tr>
  <td><%= link_to listing.title, listing %></td>
  <td><%= pluralize listing.bids.count, 'bid' %></td>
  <td>
    <% if listing.highest_bid %>
    <strong><%= number_to_currency(listing.highest_bid.amount) %></strong>
    <% end %>
  </td>
  <td>
    <% if listing.active? %>
      <%= distance_of_time_in_words_to_now listing.end_at, true %>
    <% else %>
      <%= listing.end_at.to_s(:listing) %>
    <% end %>
  </td>
</tr>

app/views/listings/_listings.html.erb
<table class="listings">
  <thead>
    <tr>
      <th>Item</th>
      <th></th>
      <th>Amount</th>
      <th>Time remaining</th>
    </tr>
  </thead>
  <tbody>
    <%= render listings %>
  </tbody>
</table>

app/views/listings/edit.html.erb
<h2>Update your listing</h2>

<%= render 'form' %>

app/views/listings/index.html.erb
<h1>Listings</h1>
<%= link_to 'New Listing', new_listing_path %>

<%= render 'listings', :listings => @listings %>

app/views/listings/new.html.erb
<h2>Create a new listing…</h2>

<%= render 'form' %>

app/views/listings/show.html.erb
<h2><%= @listing.title %></h2>

<%= render 'info' %>

<div class="description">
  <%= @listing.description %>
</div>

<div id="bid">
  <h3>Place a bid</h3>
  <% if user_signed_in? %>
    <%= render 'bids/form' %>
  <% else %>
    <p><%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to place a bid.</p>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form.error_messages %>
<div class="text_field">
  <%= form.label :nickname %>
  <%= form.text_field :nickname %>
</div>
<div class="text_field">
  <%= form.label :email %>
  <%= form.text_field :email %>
</div>
<div class="password_field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
<div class="password_field">
  <%= form.label :password_confirmation, "Confirm password" %>
  <%= form.password_field :password_confirmation %>
</div>
<div class="select_field">
  <%= form.label :time_zone %>
  <%= form.time_zone_select 'time_zone', ActiveSupport::TimeZone.us_zones, :default => 'Eastern Time (US & Canada)' %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<% form_for @user, :url => profile_path do |form| %>
  <%= render form %>
  <%= form.submit 'Save' %>
<% end %>

app/views/users/show.html.erb
<h2><%=h @user %></h2>
<% if current_user == @user %>
  <%= link_to 'Edit', edit_profile_path %>
<% end %>

<h3>Listings</h3>

<%= render 'listings/listings', :object => @user.listings %>